sudo: false
addons:
  apt:
    packages:
      - libxml2-dev
      - libjson-c-dev
      - libreadline-dev
      - valgrind
      - libtool-bin
install:
  - ./autogen.sh
  - sed -i '41s/ENOENT/ENOENT || errno == EINVAL/' gnulib/tests/test-readlink.h
language: c
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#augeas"
script: ./configure && make && make check VERBOSE=1 && ./src/try valgrind
